# Generated by Django 4.2.13 on 2024-08-16 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoclubapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='rnd',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='edad',
            new_name='fono',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_de_nacimiento',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='sueldo',
        ),
    ]
